set_property PACKAGE_PIN R11 [get_ports {key_wei}]
set_property PACKAGE_PIN R17 [get_ports {key_shuzi}]
set_property PACKAGE_PIN R15 [get_ports {key_enter}]
set_property PACKAGE_PIN V1 [get_ports {key_input}]
set_property PACKAGE_PIN U4 [get_ports {key_disp}]
set_property PACKAGE_PIN P4 [get_ports {key_rd}]

set_property PACKAGE_PIN G1 [get_ports {pos_b[3]}]
set_property PACKAGE_PIN F1 [get_ports {pos_b[2]}]
set_property PACKAGE_PIN E1 [get_ports {pos_b[1]}]
set_property PACKAGE_PIN G6 [get_ports {pos_b[0]}]
set_property PACKAGE_PIN H2 [get_ports {seg_b[7]}]
set_property PACKAGE_PIN D2 [get_ports {seg_b[6]}]
set_property PACKAGE_PIN E2 [get_ports {seg_b[5]}]
set_property PACKAGE_PIN F3 [get_ports {seg_b[4]}]
set_property PACKAGE_PIN F4 [get_ports {seg_b[3]}]
set_property PACKAGE_PIN D3 [get_ports {seg_b[2]}]
set_property PACKAGE_PIN E3 [get_ports {seg_b[1]}]
set_property PACKAGE_PIN D4 [get_ports {seg_b[0]}]

set_property PACKAGE_PIN G2 [get_ports {pos_f[3]}]
set_property PACKAGE_PIN C2 [get_ports {pos_f[2]}]
set_property PACKAGE_PIN C1 [get_ports {pos_f[1]}]
set_property PACKAGE_PIN H1 [get_ports {pos_f[0]}]
set_property PACKAGE_PIN D5 [get_ports {seg_f[7]}]
set_property PACKAGE_PIN B2 [get_ports {seg_f[6]}]
set_property PACKAGE_PIN B3 [get_ports {seg_f[5]}]
set_property PACKAGE_PIN A1 [get_ports {seg_f[4]}]
set_property PACKAGE_PIN B1 [get_ports {seg_f[3]}]
set_property PACKAGE_PIN A3 [get_ports {seg_f[2]}]
set_property PACKAGE_PIN A4 [get_ports {seg_f[1]}]
set_property PACKAGE_PIN B4 [get_ports {seg_f[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {key_wei}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_shuzi}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_enter}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_input}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_disp}]

set_property IOSTANDARD LVCMOS33 [get_ports {pos_f[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pos_f[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pos_f[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pos_f[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pos_b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pos_b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pos_b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pos_b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_f[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_f[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_f[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_f[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_f[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_f[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_f[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_f[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_b[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_b[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_b[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_b[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_b[0]}]
set_property PACKAGE_PIN P17 [get_ports clk100mhz]
set_property PACKAGE_PIN P5 [get_ports clr]
set_property IOSTANDARD LVCMOS33 [get_ports clk100mhz]
set_property IOSTANDARD LVCMOS33 [get_ports clr]

set_property -dict {PACKAGE_PIN L15 IOSTANDARD LVCMOS33} [get_ports {sram_addr[18]}]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33} [get_ports {sram_addr[17]}]
set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVCMOS33} [get_ports {sram_addr[16]}]
set_property -dict {PACKAGE_PIN M18 IOSTANDARD LVCMOS33} [get_ports {sram_addr[15]}]
set_property -dict {PACKAGE_PIN R12 IOSTANDARD LVCMOS33} [get_ports {sram_addr[14]}]
set_property -dict {PACKAGE_PIN R13 IOSTANDARD LVCMOS33} [get_ports {sram_addr[13]}]
set_property -dict {PACKAGE_PIN M13 IOSTANDARD LVCMOS33} [get_ports {sram_addr[12]}]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS33} [get_ports {sram_addr[11]}]
set_property -dict {PACKAGE_PIN T18 IOSTANDARD LVCMOS33} [get_ports {sram_addr[10]}]
set_property -dict {PACKAGE_PIN N14 IOSTANDARD LVCMOS33} [get_ports {sram_addr[9]}]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33} [get_ports {sram_addr[8]}]
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports {sram_addr[7]}]
set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVCMOS33} [get_ports {sram_addr[6]}]
set_property -dict {PACKAGE_PIN M16 IOSTANDARD LVCMOS33} [get_ports {sram_addr[5]}]
set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVCMOS33} [get_ports {sram_addr[4]}]
set_property -dict {PACKAGE_PIN N15 IOSTANDARD LVCMOS33} [get_ports {sram_addr[3]}]
set_property -dict {PACKAGE_PIN N16 IOSTANDARD LVCMOS33} [get_ports {sram_addr[2]}]
set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS33} [get_ports {sram_addr[1]}]
set_property -dict {PACKAGE_PIN T15 IOSTANDARD LVCMOS33} [get_ports {sram_addr[0]}]

set_property -dict {PACKAGE_PIN V15 IOSTANDARD LVCMOS33} [get_ports sram_ce_n]
set_property -dict {PACKAGE_PIN R10 IOSTANDARD LVCMOS33} [get_ports sram_lb_n]
set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVCMOS33} [get_ports sram_oe_n]
set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVCMOS33} [get_ports sram_ub_n]
set_property -dict {PACKAGE_PIN V16 IOSTANDARD LVCMOS33} [get_ports sram_we_n]

set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS33} [get_ports {sram_data[15]}]
set_property -dict {PACKAGE_PIN T9  IOSTANDARD LVCMOS33} [get_ports {sram_data[14]}]
set_property -dict {PACKAGE_PIN U13 IOSTANDARD LVCMOS33} [get_ports {sram_data[13]}]
set_property -dict {PACKAGE_PIN T13 IOSTANDARD LVCMOS33} [get_ports {sram_data[12]}]
set_property -dict {PACKAGE_PIN V14 IOSTANDARD LVCMOS33} [get_ports {sram_data[11]}]
set_property -dict {PACKAGE_PIN U14 IOSTANDARD LVCMOS33} [get_ports {sram_data[10]}]
set_property -dict {PACKAGE_PIN V11 IOSTANDARD LVCMOS33} [get_ports {sram_data[9]}]
set_property -dict {PACKAGE_PIN V10 IOSTANDARD LVCMOS33} [get_ports {sram_data[8]}]
set_property -dict {PACKAGE_PIN V12 IOSTANDARD LVCMOS33} [get_ports {sram_data[7]}]
set_property -dict {PACKAGE_PIN U12 IOSTANDARD LVCMOS33} [get_ports {sram_data[6]}]
set_property -dict {PACKAGE_PIN U11 IOSTANDARD LVCMOS33} [get_ports {sram_data[5]}]
set_property -dict {PACKAGE_PIN T11 IOSTANDARD LVCMOS33} [get_ports {sram_data[4]}]
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS33} [get_ports {sram_data[3]}]
set_property -dict {PACKAGE_PIN U16 IOSTANDARD LVCMOS33} [get_ports {sram_data[2]}]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports {sram_data[1]}]
set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVCMOS33} [get_ports {sram_data[0]}]
