set_property PACKAGE_PIN P5 [get_ports {kin1}]
set_property PACKAGE_PIN P4 [get_ports {kin2}]
set_property PACKAGE_PIN P3 [get_ports {kin3}]
set_property PACKAGE_PIN P2 [get_ports {kin4}]
set_property PACKAGE_PIN R2 [get_ports {kin1_up}]
set_property PACKAGE_PIN M4 [get_ports {kin2_up}]
set_property PACKAGE_PIN N4 [get_ports {kin2_down}]
set_property PACKAGE_PIN R1 [get_ports {kin3_up}]
set_property PACKAGE_PIN R11 [get_ports {kin3_down}]
set_property PACKAGE_PIN R17 [get_ports {kin4_down}]
set_property IOSTANDARD LVCMOS33 [get_ports {kin1}]
set_property IOSTANDARD LVCMOS33 [get_ports {kin2}]
set_property IOSTANDARD LVCMOS33 [get_ports {kin3}]
set_property IOSTANDARD LVCMOS33 [get_ports {kin4}]
set_property IOSTANDARD LVCMOS33 [get_ports {kin1_up}]
set_property IOSTANDARD LVCMOS33 [get_ports {kin2_up}]
set_property IOSTANDARD LVCMOS33 [get_ports {kin2_down}]
set_property IOSTANDARD LVCMOS33 [get_ports {kin3_up}]
set_property IOSTANDARD LVCMOS33 [get_ports {kin3_down}]
set_property IOSTANDARD LVCMOS33 [get_ports {kin4_down}]


set_property PACKAGE_PIN G1 [get_ports {pos[3]}]
set_property PACKAGE_PIN F1 [get_ports {pos[2]}]
set_property PACKAGE_PIN E1 [get_ports {pos[1]}]
set_property PACKAGE_PIN G6 [get_ports {pos[0]}]
set_property PACKAGE_PIN H2 [get_ports {seg[7]}]
set_property PACKAGE_PIN D2 [get_ports {seg[6]}]
set_property PACKAGE_PIN E2 [get_ports {seg[5]}]
set_property PACKAGE_PIN F3 [get_ports {seg[4]}]
set_property PACKAGE_PIN F4 [get_ports {seg[3]}]
set_property PACKAGE_PIN D3 [get_ports {seg[2]}]
set_property PACKAGE_PIN E3 [get_ports {seg[1]}]
set_property PACKAGE_PIN D4 [get_ports {seg[0]}]

set_property -dict {PACKAGE_PIN F6 IOSTANDARD LVCMOS33} [get_ports {led[0]}]
set_property -dict {PACKAGE_PIN G4 IOSTANDARD LVCMOS33} [get_ports {led[1]}]
set_property -dict {PACKAGE_PIN G3 IOSTANDARD LVCMOS33} [get_ports {led[2]}]
set_property -dict {PACKAGE_PIN J4 IOSTANDARD LVCMOS33} [get_ports {led[3]}]
set_property -dict {PACKAGE_PIN H4 IOSTANDARD LVCMOS33} [get_ports {led[4]}]
set_property -dict {PACKAGE_PIN J3 IOSTANDARD LVCMOS33} [get_ports {led[5]}]
set_property -dict {PACKAGE_PIN J2 IOSTANDARD LVCMOS33} [get_ports {led[6]}]
set_property -dict {PACKAGE_PIN K2 IOSTANDARD LVCMOS33} [get_ports {led[7]}]


set_property IOSTANDARD LVCMOS33 [get_ports {pos[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pos[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pos[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pos[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property PACKAGE_PIN P17 [get_ports clk100mhz]
set_property PACKAGE_PIN R15 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports clk100mhz]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
